### ISSUE TITLE
Deprecation

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bip32-wallet#10]
Deprecate this module in favour of https://github.com/bitcoinjs/bip32-utils

**Comment by dcousens** [comment]
Deprecated for `0.7.1`

**Comment by fanatid** [comment]
https://docs.npmjs.com/cli/deprecate

**Comment by dcousens** [comment]
@fanatid I did that?

**Comment by fanatid** [comment]
Sorry, I should be more clear.
In additional to deprecation message in README you also can set deprecation message on npm with deprecate command.

**Comment by dcousens** [comment]
@fanatid I did both AFAIK
