### ISSUE TITLE
Discussion: 0.5.0 and a future merge with bip32-utils

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bip32-wallet#6]
The `Wallet` abstraction is merely another form of BIP32 key management, and probably could be merged with `Account` and `Chain` in https://github.com/bitcoinjs/bip32-utils.

It'd be nice to extract the [`safe-transaction`](https://github.com/bitcoinjs/bip32-wallet/blob/master/index.js#L59-L127) code out to a new module,  without giving up the interface simplicity.
It currently makes up the most of this module, and is the most extensively tested.

With the removal of unspents management [in 0.5.0], `Wallet` is now just a wrapper around a BIP32 `Account`,  with a well tested transaction creation function.

The https://github.com/dcousens/coinselect package extraction was just one part of this.

If anyone else uses this package,  I'd be interested to hear your thoughts on this.

**Comment by dcousens** [comment]
For what its worth, these changes are all based around increasing functionality while maintaining encapsulation.
In `0.4.x`, `Wallet` as an abstraction was doing:

* Input selection
* Key management (backed by `bip32-utils` account)
* Unspent management
* Transaction creation

 The single responsibility principle,  while by no means a law,  is violated by this broad range of responsibilities.

In `0.4.3`,  `Input selection` was extracted to [`coinselect`](https://github.com/dcousens/coinselect), but the overall responsibility remained the same.

In `0.5.0`,  `Unspent management` and `Input selection` was removed entirely,  with the user expected to do this themselves (just use the `coinSelect` module).

``` javascript
var selection = coinSelect(unspents, outputs, feePerKb)
var transaction = wallet.createTransaction(selection.inputs, outputs, selection.fee)

// ...
```

For `>0.5.0`,  this leaves us with `Transaction creation` as the last non-key management related responsibility.

I don't want to move too far away from a powerful API,  and force module hell on users,  but,  perhaps theres a way to achieve these goals

Open to discussion,  and I'd appreciate if any users of this module would speak out :+1:

**Comment by dcousens** [comment]
@jprichardson any thoughts?

**Comment by dcousens** [comment]
One example where the `safe-transaction` module would be best in isolation, is in how actual users (including myself) [would prefer to use it](https://github.com/joshmh/yakutsk/blob/43589f7561d008b1610244da724221607d3fcd09/hot/bin/wallet#L165-L211).

**Comment by joshmh** [comment]
@dcousens, thanks for looping me in. I like this idea. I had to adapt the createTransaction part because it was tied to the unspent inputs and didn't support the fancy HD multi-sig stuff I was working on. With this architecture, I'd be able to just use the bip32 module as-is.

Coin selection is a complex part of the process that's been somewhat neglected by the bitcoin dev community, so I think it's smart to break it out into its own module.

**Comment by dcousens** [comment]
This module is soon to be deprecated.

https://github.com/bitcoinjs/bip32-utils `Account` does most of it minus `buildTransaction`... which I'm still figuring out the best alternative.

It is **very** limiting to use `buildTransaction` as is since it forces you to give up most of the capabilities of `TransactionBuilder`, when really software that uses those tools should be flexible.
But that said,  `TransactionBuilder` doesn't have any sanity around fee error handling (as it shouldn't!) nor does it handle things like BIP69.

I think maybe, just maybe that is where we draw the line as to what applications should be implementing themselves.
But, we'll see... maybe in another 12 months.
