### ISSUE TITLE
Missing function

### ISSUE THREAD

**Issue by devluxg** [bitcoinjs/bip32-wallet#7]
Sorry for making this an issue, I wanted to do a PR, but my repo is borked. 
I didn't fork properly or something.  

Anyways, could you please consider adding something along the following to wallet.js 
It is required if one is rebuilding a wallet from a known seed.  Super useful to have and I'm not at all sure why it's missing.

`Wallet.fromSeedHex = function(hex,network){
  var m = bitcoin.HDNode.fromSeedHex(hex, network)
  var i = m.deriveHardened(0)
  var external = i.derive(0)
  var internal = i.derive(1)
  return new HDWallet.Wallet(external, internal)
}`

Thanks!

**Comment by dcousens** [comment]
Any reason not to use `fromSeedBuffer`?

**Comment by devluxg** [comment]
new Buffer is relying on node style buffers.  That won't necessarily be present browser side or exported at the level where Wallet is being used.  This little change makes it useful without having to include node buffers.

**Comment by fanatid** [comment]
@devluxg but `bitcoin.HDNode.fromSeedHex` uses `Buffer`: https://github.com/bitcoinjs/bitcoinjs-lib/blob/0cedacddc62718adaf22d3c5c094e51e149d0259/src/hdnode.js#L50

**Comment by dcousens** [comment]
@devluxg `Buffer` will be used regardless... `Buffer` is used throughout the entire `bitcoinjs-lib` stack,  and even in the ECDSA stack.
You're not adding anything that isn't already there if you use any of the other libraries.

**Comment by devluxg** [comment]
No it's more or less a matter of explicitly exposing it and getting things that aren't node derived to play nicely with node buffers.  

Also if you're doing this a lot it's an extra step to setup and tear down the buffer 2x like that.  I guess it depends on your use case, but here I'm conserving ram despite having possibly 10s of thousands of seeds, by caching them to localstorage when they aren't actively needed.  (everything I'm sticking into local storage is being encrypted in the browser using crypto subtle).
I'm chossing crypto subtle here because I benchmarked it vs the nodelibs and there just wasn't even a comparison to be made.  We're talking 20 keys per min vs a few hundred using nodelibs.

This gives me a choice of string or Uint8Array, it will not take node Buffer at that stage which means I have to copy the string into a node buffer after already setting up a typed array for the decryption step.

Does this make sense?

It's a very simple add on which as far as I can tell is perfectly safe.  I realize that buffers are used throughout the entire library, but when I'm dealing with keyhandling in the browser the node buffers don't seem to play nice.  Adding this makes it easier for me and possibly anyone else who is trying to optimize performance by using the browser native calls wherever possible.

Thanks!

**Comment by dcousens** [comment]
> Also if you're doing this a lot it's an extra step to setup and tear down the buffer 2x like that

What?  There is only 1 `Buffer` being used.

> This gives me a choice of string or Uint8Array, it will not take node Buffer at that stage which means I have to copy the string into a node buffer after already setting up a typed array for the decryption step.

`Buffer` is usually `UInt8Array` but slightly extended.

> It's a very simple add on which as far as I can tell is perfectly safe. I realize that buffers are used throughout the entire library, but when I'm dealing with keyhandling in the browser the node buffers don't seem to play nice.

I mean sure,  I'm not against it,  it just seems redundant.

**Comment by devluxg** [comment]
Try encrypting a hex seed using crypto.subtle then decrypting it and building a wallet.  Something gets wonky.  crypto.subtle doesn't like it when you pass in a node buffer and the wallet won't take the UInt8Array coming out of crypto.subtle.  Hex string seems to be the correct answer.

If this were a random library off the internet I would agree, but this is the only method of encryption directly built into the browser and it's highly accelerated and seems to be more agressive about memory management as well.

**Comment by fanatid** [comment]
How `crypto.subtle` widely spread? It will hard to maintain one method with specific code which also will use polyfill.

For crypto I'd prefer use one code everywhere is possible (pure js code). With `crypto.sublle` we will have 3 implementations: node (c/c++), pure js, browser crypto. Are you sure that they implement all things right? Do they repeat bugs from other implementations?

**Comment by dcousens** [comment]
@devluxg sure,  but I'm still not seeing why that means you can't just use a `Buffer` yourself rather than us pushing:

``` javascript
BIP32Wallet.prototype.fromSeedHex = function (hex, ...) {
  return BIP32Wallet.prototype.fromSeedBuffer(new Buffer(hex, 'hex'), ...)
}

**Comment by devluxg** [comment]
@fanatid Uhh it is the standard I'm unaware of any recent browser that does not support it already.
https://developer.mozilla.org/en/docs/Web/API/SubtleCrypto

That said, I'm not asking you to migrate to it, or even support it directly.  I'm saying having the wallet take a hex encoded string is a really super handy thing and here's a reason why.

**Comment by devluxg** [comment]
@dcousens The reason why is that it is a very simple addon that it enhances the utility of the library for me and I doubt I'm the only one.  It introduces no security vulnerabilities and it saves every single one of your users from having to dig in and sort out the correct way of doing it.  For example, I already do have code that does this, admittedly yours looks a lot cleaner and better.  I'm a decent coder and it took me a solid 30 minutes to realize that this function was not there then sort out a way of doing it myself.

If nothing else you're helping us to all be a little tiny bit lazier which means we can all go home and drink a beer at the end of the day rather than scratching our heads at 5PM going "what?  there's no method that just takes a string?"  :)

**Comment by dcousens** [comment]
@devluxg no worries :),  take the code above,  put it in a PR,  and I'll merge it and release :+1:
